apiVersion: v1
kind: Service
metadata:
  name: {{.Values.services.loadBalancer.name}}
  namespace: {{.Values.namespace}}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    external-dns.alpha.kubernetes.io/hostname: {{.Values.services.loadBalancer.name}}.memodapp.com
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{.Values.lbSSLCert}}
    # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{.Values.lbSSLCert}}
    # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    # service.beta.kubernetes.io/aws-load-balancer-name: template-apidevops
spec:
  selector:
    app: {{.Values.services.loadBalancer.appName}}
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80